### ISSUE TITLE
A few thoughts on what to improve

### ISSUE THREAD

**Issue by b1ek** [Redbeardjunior/Dock#1]
Hiii!! First of all, I want to say that it's great that you want to learn new things and do projects like this to show people.

But there are a few things that definetely would need improving here:

1\. Absolute paths in your `docker-compose.yml` file, maybe in other files (i haven't studied it that far), just like lines 24-25:  
```yml
volumes:
    - C:\Program Files\Dock\nginx\nginx.conf:/etc/nginx/conf.d/default.conf
```

How am i supposed to know that im supposed to clone the project into `C:\Program Files` directory, if that's not mentioned anywhere in the `README.md`? Also i have no idea how did you got docker running on windows, but keep in mind that in the most cases it would be a linux machine running your code.

To prevent these kinds of situations, you could've used an absolute path, just like this:  
```yml
volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
```

That way, your OS would automatically replace the `.` with the current directory your docker-compose file is in. For example, let's say that your docker-compose file is in the `C:\Users\CoolGuy\Desktop\docker-compose.yml`, then the `./nginx/nginx.conf` would resolve to `C:\Users\CoolGuy\Desktop\nginx\nginx.conf`.

2\. The app/node_1 dockerfile

A few lines here confuse me:

1. Why are you installing only `express` via [`npm install express`](https://github.com/Redbeardjunior/Dock/blob/e14fa3a4cb684c7b36b9d8b895a696373b6ab9e7/app/node_1/Dockerfile#L4)? Wouldn't you also have other packages to install?
2. For some reason, you copy files **after** you install the packages in Dockerfile. Lets imagine a situation when you are running a linux VM with docker to run the code, then you install node_modules in windows. And when you copy those host modules in linux (dockerfile code would run in the linux VM), it would copy those windows modules into the linux VM. Doesnt sound very good to me.
3. Also you don't need to do 2 COPYs to first copy the `package*.json`, and then the rest. You could copy the whole thing in just one `COPY . .` instruction and don't bloat up the lines

3\. The readme

Seriously, did you even read it when you wrote it? The logic there is completely broken, and if you are creating an open source project the first thing that you would want to do is to make a proper readme with documentation and different examples.

Overall, it looks like a rather good starter project, but definetely better than my first ones.
In any way, I hope that you will go far in the dev field and have great success!

**Comment by Redbeardjunior** [comment]
First of all, @b1ek, thank you for taking the time and effort to look over my project and provide your feedback. I truly appreciate your thoughtful insights and suggestions for improvement. It's evident that you've given the project a thorough review, and your feedback is incredibly valuable in helping me enhance the quality and usability of the project.

Regarding your points:

1. Absolute Paths: You're absolutely right, using absolute paths in the Docker Compose file can cause compatibility issues and confusion across different systems. Your suggestion to use relative paths with the ./nginx/nginx.conf notation is excellent. This would ensure greater portability and make it easier for users to understand and set up the project.

2. Dockerfile Structure: Your observations about the Dockerfile are spot on. It's clear that copying the node modules from a Windows environment to a Linux-based Docker container is not optimal. Your suggestion to consolidate the copying into a single instruction is practical and would make the Dockerfile cleaner. Also, I appreciate your point about potentially needing to install more packages in the future.

3. README Quality: I acknowledge your feedback about the quality of the README. You're absolutely right that clear documentation and examples are crucial for an open source project. I apologize for the oversight in my initial README and I'll certainly work on providing a more comprehensive and logically structured README that provides users with the necessary information to understand and use the project effectively.

I'm truly grateful for your encouragement and your hopes for my success in the field of development. Your feedback is a valuable stepping stone in improving my project and my skills as a developer. If you have any further suggestions or advice, please don't hesitate to share. Thank you once again for your time and insights!

**Comment by b1ek** [comment]
@Redbeardjunior if you would need any advice in absolutely anything, feel free to contact me via one of my contacts shown at my [profile readme](https://github.com/b1ek), IIRC they are all current
